/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_fun_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[159] = {155, 1, 0, 155, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154};
static const int casadi_s3[4] = {0, 1, 0, 0};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* f_fun:(states[4],controls,params[155],alg[0])->(xdot[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a1;
  casadi_real a2=9.8100000000000005e+000;
  casadi_real a3=arg[2] ? arg[2][1] : 0;
  casadi_real a4=(a2*a3);
  casadi_real a5=arg[0] ? arg[0][1] : 0;
  casadi_real a6=cos(a5);
  a4=(a4*a6);
  a6=sin(a5);
  a4=(a4*a6);
  a6=arg[2] ? arg[2][2] : 0;
  casadi_real a7=(a3*a6);
  casadi_real a8=sin(a5);
  a7=(a7*a8);
  a8=sq(a1);
  a7=(a7*a8);
  a4=(a4-a7);
  a7=arg[1] ? arg[1][0] : 0;
  a4=(a4+a7);
  a8=arg[2] ? arg[2][0] : 0;
  casadi_real a9=(a8+a3);
  casadi_real a10=cos(a5);
  a10=sq(a10);
  a10=(a3*a10);
  a9=(a9-a10);
  a4=(a4/a9);
  a10=arg[2] ? arg[2][3] : 0;
  a4=(a4*a10);
  casadi_real a11=arg[2] ? arg[2][4] : 0;
  casadi_real a12=arg[2] ? arg[2][5] : 0;
  casadi_real a13=arg[0] ? arg[0][0] : 0;
  casadi_real a14=(a12-a13);
  a14=sq(a14);
  casadi_real a15=arg[2] ? arg[2][125] : 0;
  a15=sq(a15);
  a14=(a14/a15);
  casadi_real a16=arg[2] ? arg[2][25] : 0;
  casadi_real a17=(a16-a5);
  a17=sq(a17);
  casadi_real a18=arg[2] ? arg[2][126] : 0;
  a18=sq(a18);
  a17=(a17/a18);
  a14=(a14+a17);
  a17=arg[2] ? arg[2][45] : 0;
  casadi_real a19=(a17-a0);
  a19=sq(a19);
  casadi_real a20=arg[2] ? arg[2][127] : 0;
  a20=sq(a20);
  a19=(a19/a20);
  a14=(a14+a19);
  a19=arg[2] ? arg[2][65] : 0;
  casadi_real a21=(a19-a1);
  a21=sq(a21);
  casadi_real a22=arg[2] ? arg[2][128] : 0;
  a22=sq(a22);
  a21=(a21/a22);
  a14=(a14+a21);
  a21=arg[2] ? arg[2][85] : 0;
  casadi_real a23=(a21-a7);
  a23=sq(a23);
  casadi_real a24=arg[2] ? arg[2][129] : 0;
  a24=sq(a24);
  a23=(a23/a24);
  a14=(a14+a23);
  a14=(-a14);
  a14=exp(a14);
  a23=arg[2] ? arg[2][105] : 0;
  a14=(a14*a23);
  a23=arg[2] ? arg[2][6] : 0;
  casadi_real a25=(a23-a13);
  a25=sq(a25);
  a25=(a25/a15);
  casadi_real a26=arg[2] ? arg[2][26] : 0;
  casadi_real a27=(a26-a5);
  a27=sq(a27);
  a27=(a27/a18);
  a25=(a25+a27);
  a27=arg[2] ? arg[2][46] : 0;
  casadi_real a28=(a27-a0);
  a28=sq(a28);
  a28=(a28/a20);
  a25=(a25+a28);
  a28=arg[2] ? arg[2][66] : 0;
  casadi_real a29=(a28-a1);
  a29=sq(a29);
  a29=(a29/a22);
  a25=(a25+a29);
  a29=arg[2] ? arg[2][86] : 0;
  casadi_real a30=(a29-a7);
  a30=sq(a30);
  a30=(a30/a24);
  a25=(a25+a30);
  a25=(-a25);
  a25=exp(a25);
  a30=arg[2] ? arg[2][106] : 0;
  a25=(a25*a30);
  a14=(a14+a25);
  a25=arg[2] ? arg[2][7] : 0;
  a30=(a25-a13);
  a30=sq(a30);
  a30=(a30/a15);
  casadi_real a31=arg[2] ? arg[2][27] : 0;
  casadi_real a32=(a31-a5);
  a32=sq(a32);
  a32=(a32/a18);
  a30=(a30+a32);
  a32=arg[2] ? arg[2][47] : 0;
  casadi_real a33=(a32-a0);
  a33=sq(a33);
  a33=(a33/a20);
  a30=(a30+a33);
  a33=arg[2] ? arg[2][67] : 0;
  casadi_real a34=(a33-a1);
  a34=sq(a34);
  a34=(a34/a22);
  a30=(a30+a34);
  a34=arg[2] ? arg[2][87] : 0;
  casadi_real a35=(a34-a7);
  a35=sq(a35);
  a35=(a35/a24);
  a30=(a30+a35);
  a30=(-a30);
  a30=exp(a30);
  a35=arg[2] ? arg[2][107] : 0;
  a30=(a30*a35);
  a14=(a14+a30);
  a30=arg[2] ? arg[2][8] : 0;
  a35=(a30-a13);
  a35=sq(a35);
  a35=(a35/a15);
  casadi_real a36=arg[2] ? arg[2][28] : 0;
  casadi_real a37=(a36-a5);
  a37=sq(a37);
  a37=(a37/a18);
  a35=(a35+a37);
  a37=arg[2] ? arg[2][48] : 0;
  casadi_real a38=(a37-a0);
  a38=sq(a38);
  a38=(a38/a20);
  a35=(a35+a38);
  a38=arg[2] ? arg[2][68] : 0;
  casadi_real a39=(a38-a1);
  a39=sq(a39);
  a39=(a39/a22);
  a35=(a35+a39);
  a39=arg[2] ? arg[2][88] : 0;
  casadi_real a40=(a39-a7);
  a40=sq(a40);
  a40=(a40/a24);
  a35=(a35+a40);
  a35=(-a35);
  a35=exp(a35);
  a40=arg[2] ? arg[2][108] : 0;
  a35=(a35*a40);
  a14=(a14+a35);
  a35=arg[2] ? arg[2][9] : 0;
  a40=(a35-a13);
  a40=sq(a40);
  a40=(a40/a15);
  casadi_real a41=arg[2] ? arg[2][29] : 0;
  casadi_real a42=(a41-a5);
  a42=sq(a42);
  a42=(a42/a18);
  a40=(a40+a42);
  a42=arg[2] ? arg[2][49] : 0;
  casadi_real a43=(a42-a0);
  a43=sq(a43);
  a43=(a43/a20);
  a40=(a40+a43);
  a43=arg[2] ? arg[2][69] : 0;
  casadi_real a44=(a43-a1);
  a44=sq(a44);
  a44=(a44/a22);
  a40=(a40+a44);
  a44=arg[2] ? arg[2][89] : 0;
  casadi_real a45=(a44-a7);
  a45=sq(a45);
  a45=(a45/a24);
  a40=(a40+a45);
  a40=(-a40);
  a40=exp(a40);
  a45=arg[2] ? arg[2][109] : 0;
  a40=(a40*a45);
  a14=(a14+a40);
  a40=arg[2] ? arg[2][10] : 0;
  a45=(a40-a13);
  a45=sq(a45);
  a45=(a45/a15);
  casadi_real a46=arg[2] ? arg[2][30] : 0;
  casadi_real a47=(a46-a5);
  a47=sq(a47);
  a47=(a47/a18);
  a45=(a45+a47);
  a47=arg[2] ? arg[2][50] : 0;
  casadi_real a48=(a47-a0);
  a48=sq(a48);
  a48=(a48/a20);
  a45=(a45+a48);
  a48=arg[2] ? arg[2][70] : 0;
  casadi_real a49=(a48-a1);
  a49=sq(a49);
  a49=(a49/a22);
  a45=(a45+a49);
  a49=arg[2] ? arg[2][90] : 0;
  casadi_real a50=(a49-a7);
  a50=sq(a50);
  a50=(a50/a24);
  a45=(a45+a50);
  a45=(-a45);
  a45=exp(a45);
  a50=arg[2] ? arg[2][110] : 0;
  a45=(a45*a50);
  a14=(a14+a45);
  a45=arg[2] ? arg[2][11] : 0;
  a50=(a45-a13);
  a50=sq(a50);
  a50=(a50/a15);
  casadi_real a51=arg[2] ? arg[2][31] : 0;
  casadi_real a52=(a51-a5);
  a52=sq(a52);
  a52=(a52/a18);
  a50=(a50+a52);
  a52=arg[2] ? arg[2][51] : 0;
  casadi_real a53=(a52-a0);
  a53=sq(a53);
  a53=(a53/a20);
  a50=(a50+a53);
  a53=arg[2] ? arg[2][71] : 0;
  casadi_real a54=(a53-a1);
  a54=sq(a54);
  a54=(a54/a22);
  a50=(a50+a54);
  a54=arg[2] ? arg[2][91] : 0;
  casadi_real a55=(a54-a7);
  a55=sq(a55);
  a55=(a55/a24);
  a50=(a50+a55);
  a50=(-a50);
  a50=exp(a50);
  a55=arg[2] ? arg[2][111] : 0;
  a50=(a50*a55);
  a14=(a14+a50);
  a50=arg[2] ? arg[2][12] : 0;
  a55=(a50-a13);
  a55=sq(a55);
  a55=(a55/a15);
  casadi_real a56=arg[2] ? arg[2][32] : 0;
  casadi_real a57=(a56-a5);
  a57=sq(a57);
  a57=(a57/a18);
  a55=(a55+a57);
  a57=arg[2] ? arg[2][52] : 0;
  casadi_real a58=(a57-a0);
  a58=sq(a58);
  a58=(a58/a20);
  a55=(a55+a58);
  a58=arg[2] ? arg[2][72] : 0;
  casadi_real a59=(a58-a1);
  a59=sq(a59);
  a59=(a59/a22);
  a55=(a55+a59);
  a59=arg[2] ? arg[2][92] : 0;
  casadi_real a60=(a59-a7);
  a60=sq(a60);
  a60=(a60/a24);
  a55=(a55+a60);
  a55=(-a55);
  a55=exp(a55);
  a60=arg[2] ? arg[2][112] : 0;
  a55=(a55*a60);
  a14=(a14+a55);
  a55=arg[2] ? arg[2][13] : 0;
  a60=(a55-a13);
  a60=sq(a60);
  a60=(a60/a15);
  casadi_real a61=arg[2] ? arg[2][33] : 0;
  casadi_real a62=(a61-a5);
  a62=sq(a62);
  a62=(a62/a18);
  a60=(a60+a62);
  a62=arg[2] ? arg[2][53] : 0;
  casadi_real a63=(a62-a0);
  a63=sq(a63);
  a63=(a63/a20);
  a60=(a60+a63);
  a63=arg[2] ? arg[2][73] : 0;
  casadi_real a64=(a63-a1);
  a64=sq(a64);
  a64=(a64/a22);
  a60=(a60+a64);
  a64=arg[2] ? arg[2][93] : 0;
  casadi_real a65=(a64-a7);
  a65=sq(a65);
  a65=(a65/a24);
  a60=(a60+a65);
  a60=(-a60);
  a60=exp(a60);
  a65=arg[2] ? arg[2][113] : 0;
  a60=(a60*a65);
  a14=(a14+a60);
  a60=arg[2] ? arg[2][14] : 0;
  a65=(a60-a13);
  a65=sq(a65);
  a65=(a65/a15);
  casadi_real a66=arg[2] ? arg[2][34] : 0;
  casadi_real a67=(a66-a5);
  a67=sq(a67);
  a67=(a67/a18);
  a65=(a65+a67);
  a67=arg[2] ? arg[2][54] : 0;
  casadi_real a68=(a67-a0);
  a68=sq(a68);
  a68=(a68/a20);
  a65=(a65+a68);
  a68=arg[2] ? arg[2][74] : 0;
  casadi_real a69=(a68-a1);
  a69=sq(a69);
  a69=(a69/a22);
  a65=(a65+a69);
  a69=arg[2] ? arg[2][94] : 0;
  casadi_real a70=(a69-a7);
  a70=sq(a70);
  a70=(a70/a24);
  a65=(a65+a70);
  a65=(-a65);
  a65=exp(a65);
  a70=arg[2] ? arg[2][114] : 0;
  a65=(a65*a70);
  a14=(a14+a65);
  a65=arg[2] ? arg[2][15] : 0;
  a70=(a65-a13);
  a70=sq(a70);
  a70=(a70/a15);
  casadi_real a71=arg[2] ? arg[2][35] : 0;
  casadi_real a72=(a71-a5);
  a72=sq(a72);
  a72=(a72/a18);
  a70=(a70+a72);
  a72=arg[2] ? arg[2][55] : 0;
  casadi_real a73=(a72-a0);
  a73=sq(a73);
  a73=(a73/a20);
  a70=(a70+a73);
  a73=arg[2] ? arg[2][75] : 0;
  casadi_real a74=(a73-a1);
  a74=sq(a74);
  a74=(a74/a22);
  a70=(a70+a74);
  a74=arg[2] ? arg[2][95] : 0;
  casadi_real a75=(a74-a7);
  a75=sq(a75);
  a75=(a75/a24);
  a70=(a70+a75);
  a70=(-a70);
  a70=exp(a70);
  a75=arg[2] ? arg[2][115] : 0;
  a70=(a70*a75);
  a14=(a14+a70);
  a70=arg[2] ? arg[2][16] : 0;
  a75=(a70-a13);
  a75=sq(a75);
  a75=(a75/a15);
  casadi_real a76=arg[2] ? arg[2][36] : 0;
  casadi_real a77=(a76-a5);
  a77=sq(a77);
  a77=(a77/a18);
  a75=(a75+a77);
  a77=arg[2] ? arg[2][56] : 0;
  casadi_real a78=(a77-a0);
  a78=sq(a78);
  a78=(a78/a20);
  a75=(a75+a78);
  a78=arg[2] ? arg[2][76] : 0;
  casadi_real a79=(a78-a1);
  a79=sq(a79);
  a79=(a79/a22);
  a75=(a75+a79);
  a79=arg[2] ? arg[2][96] : 0;
  casadi_real a80=(a79-a7);
  a80=sq(a80);
  a80=(a80/a24);
  a75=(a75+a80);
  a75=(-a75);
  a75=exp(a75);
  a80=arg[2] ? arg[2][116] : 0;
  a75=(a75*a80);
  a14=(a14+a75);
  a75=arg[2] ? arg[2][17] : 0;
  a80=(a75-a13);
  a80=sq(a80);
  a80=(a80/a15);
  casadi_real a81=arg[2] ? arg[2][37] : 0;
  casadi_real a82=(a81-a5);
  a82=sq(a82);
  a82=(a82/a18);
  a80=(a80+a82);
  a82=arg[2] ? arg[2][57] : 0;
  casadi_real a83=(a82-a0);
  a83=sq(a83);
  a83=(a83/a20);
  a80=(a80+a83);
  a83=arg[2] ? arg[2][77] : 0;
  casadi_real a84=(a83-a1);
  a84=sq(a84);
  a84=(a84/a22);
  a80=(a80+a84);
  a84=arg[2] ? arg[2][97] : 0;
  casadi_real a85=(a84-a7);
  a85=sq(a85);
  a85=(a85/a24);
  a80=(a80+a85);
  a80=(-a80);
  a80=exp(a80);
  a85=arg[2] ? arg[2][117] : 0;
  a80=(a80*a85);
  a14=(a14+a80);
  a80=arg[2] ? arg[2][18] : 0;
  a85=(a80-a13);
  a85=sq(a85);
  a85=(a85/a15);
  casadi_real a86=arg[2] ? arg[2][38] : 0;
  casadi_real a87=(a86-a5);
  a87=sq(a87);
  a87=(a87/a18);
  a85=(a85+a87);
  a87=arg[2] ? arg[2][58] : 0;
  casadi_real a88=(a87-a0);
  a88=sq(a88);
  a88=(a88/a20);
  a85=(a85+a88);
  a88=arg[2] ? arg[2][78] : 0;
  casadi_real a89=(a88-a1);
  a89=sq(a89);
  a89=(a89/a22);
  a85=(a85+a89);
  a89=arg[2] ? arg[2][98] : 0;
  casadi_real a90=(a89-a7);
  a90=sq(a90);
  a90=(a90/a24);
  a85=(a85+a90);
  a85=(-a85);
  a85=exp(a85);
  a90=arg[2] ? arg[2][118] : 0;
  a85=(a85*a90);
  a14=(a14+a85);
  a85=arg[2] ? arg[2][19] : 0;
  a90=(a85-a13);
  a90=sq(a90);
  a90=(a90/a15);
  casadi_real a91=arg[2] ? arg[2][39] : 0;
  casadi_real a92=(a91-a5);
  a92=sq(a92);
  a92=(a92/a18);
  a90=(a90+a92);
  a92=arg[2] ? arg[2][59] : 0;
  casadi_real a93=(a92-a0);
  a93=sq(a93);
  a93=(a93/a20);
  a90=(a90+a93);
  a93=arg[2] ? arg[2][79] : 0;
  casadi_real a94=(a93-a1);
  a94=sq(a94);
  a94=(a94/a22);
  a90=(a90+a94);
  a94=arg[2] ? arg[2][99] : 0;
  casadi_real a95=(a94-a7);
  a95=sq(a95);
  a95=(a95/a24);
  a90=(a90+a95);
  a90=(-a90);
  a90=exp(a90);
  a95=arg[2] ? arg[2][119] : 0;
  a90=(a90*a95);
  a14=(a14+a90);
  a90=arg[2] ? arg[2][20] : 0;
  a95=(a90-a13);
  a95=sq(a95);
  a95=(a95/a15);
  casadi_real a96=arg[2] ? arg[2][40] : 0;
  casadi_real a97=(a96-a5);
  a97=sq(a97);
  a97=(a97/a18);
  a95=(a95+a97);
  a97=arg[2] ? arg[2][60] : 0;
  casadi_real a98=(a97-a0);
  a98=sq(a98);
  a98=(a98/a20);
  a95=(a95+a98);
  a98=arg[2] ? arg[2][80] : 0;
  casadi_real a99=(a98-a1);
  a99=sq(a99);
  a99=(a99/a22);
  a95=(a95+a99);
  a99=arg[2] ? arg[2][100] : 0;
  casadi_real a100=(a99-a7);
  a100=sq(a100);
  a100=(a100/a24);
  a95=(a95+a100);
  a95=(-a95);
  a95=exp(a95);
  a100=arg[2] ? arg[2][120] : 0;
  a95=(a95*a100);
  a14=(a14+a95);
  a95=arg[2] ? arg[2][21] : 0;
  a100=(a95-a13);
  a100=sq(a100);
  a100=(a100/a15);
  casadi_real a101=arg[2] ? arg[2][41] : 0;
  casadi_real a102=(a101-a5);
  a102=sq(a102);
  a102=(a102/a18);
  a100=(a100+a102);
  a102=arg[2] ? arg[2][61] : 0;
  casadi_real a103=(a102-a0);
  a103=sq(a103);
  a103=(a103/a20);
  a100=(a100+a103);
  a103=arg[2] ? arg[2][81] : 0;
  casadi_real a104=(a103-a1);
  a104=sq(a104);
  a104=(a104/a22);
  a100=(a100+a104);
  a104=arg[2] ? arg[2][101] : 0;
  casadi_real a105=(a104-a7);
  a105=sq(a105);
  a105=(a105/a24);
  a100=(a100+a105);
  a100=(-a100);
  a100=exp(a100);
  a105=arg[2] ? arg[2][121] : 0;
  a100=(a100*a105);
  a14=(a14+a100);
  a100=arg[2] ? arg[2][22] : 0;
  a105=(a100-a13);
  a105=sq(a105);
  a105=(a105/a15);
  casadi_real a106=arg[2] ? arg[2][42] : 0;
  casadi_real a107=(a106-a5);
  a107=sq(a107);
  a107=(a107/a18);
  a105=(a105+a107);
  a107=arg[2] ? arg[2][62] : 0;
  casadi_real a108=(a107-a0);
  a108=sq(a108);
  a108=(a108/a20);
  a105=(a105+a108);
  a108=arg[2] ? arg[2][82] : 0;
  casadi_real a109=(a108-a1);
  a109=sq(a109);
  a109=(a109/a22);
  a105=(a105+a109);
  a109=arg[2] ? arg[2][102] : 0;
  casadi_real a110=(a109-a7);
  a110=sq(a110);
  a110=(a110/a24);
  a105=(a105+a110);
  a105=(-a105);
  a105=exp(a105);
  a110=arg[2] ? arg[2][122] : 0;
  a105=(a105*a110);
  a14=(a14+a105);
  a105=arg[2] ? arg[2][23] : 0;
  a110=(a105-a13);
  a110=sq(a110);
  a110=(a110/a15);
  casadi_real a111=arg[2] ? arg[2][43] : 0;
  casadi_real a112=(a111-a5);
  a112=sq(a112);
  a112=(a112/a18);
  a110=(a110+a112);
  a112=arg[2] ? arg[2][63] : 0;
  casadi_real a113=(a112-a0);
  a113=sq(a113);
  a113=(a113/a20);
  a110=(a110+a113);
  a113=arg[2] ? arg[2][83] : 0;
  casadi_real a114=(a113-a1);
  a114=sq(a114);
  a114=(a114/a22);
  a110=(a110+a114);
  a114=arg[2] ? arg[2][103] : 0;
  casadi_real a115=(a114-a7);
  a115=sq(a115);
  a115=(a115/a24);
  a110=(a110+a115);
  a110=(-a110);
  a110=exp(a110);
  a115=arg[2] ? arg[2][123] : 0;
  a110=(a110*a115);
  a14=(a14+a110);
  a110=arg[2] ? arg[2][24] : 0;
  a115=(a110-a13);
  a115=sq(a115);
  a115=(a115/a15);
  a15=arg[2] ? arg[2][44] : 0;
  casadi_real a116=(a15-a5);
  a116=sq(a116);
  a116=(a116/a18);
  a115=(a115+a116);
  a116=arg[2] ? arg[2][64] : 0;
  a18=(a116-a0);
  a18=sq(a18);
  a18=(a18/a20);
  a115=(a115+a18);
  a18=arg[2] ? arg[2][84] : 0;
  a20=(a18-a1);
  a20=sq(a20);
  a20=(a20/a22);
  a115=(a115+a20);
  a20=arg[2] ? arg[2][104] : 0;
  a22=(a20-a7);
  a22=sq(a22);
  a22=(a22/a24);
  a115=(a115+a22);
  a115=(-a115);
  a115=exp(a115);
  a22=arg[2] ? arg[2][124] : 0;
  a115=(a115*a22);
  a14=(a14+a115);
  a14=(a11*a14);
  a4=(a4+a14);
  if (res[0]!=0) res[0][2]=a4;
  a4=cos(a5);
  a4=(a7*a4);
  a14=(a3*a6);
  a115=cos(a5);
  a14=(a14*a115);
  a115=sin(a5);
  a14=(a14*a115);
  a115=sq(a1);
  a14=(a14*a115);
  a4=(a4-a14);
  a8=(a8+a3);
  a2=(a2*a8);
  a8=sin(a5);
  a2=(a2*a8);
  a4=(a4+a2);
  a6=(a6*a9);
  a4=(a4/a6);
  a4=(a4*a10);
  a12=(a12-a13);
  a12=sq(a12);
  a10=arg[2] ? arg[2][150] : 0;
  a10=sq(a10);
  a12=(a12/a10);
  a16=(a16-a5);
  a16=sq(a16);
  a6=arg[2] ? arg[2][151] : 0;
  a6=sq(a6);
  a16=(a16/a6);
  a12=(a12+a16);
  a17=(a17-a0);
  a17=sq(a17);
  a16=arg[2] ? arg[2][152] : 0;
  a16=sq(a16);
  a17=(a17/a16);
  a12=(a12+a17);
  a19=(a19-a1);
  a19=sq(a19);
  a17=arg[2] ? arg[2][153] : 0;
  a17=sq(a17);
  a19=(a19/a17);
  a12=(a12+a19);
  a21=(a21-a7);
  a21=sq(a21);
  a19=arg[2] ? arg[2][154] : 0;
  a19=sq(a19);
  a21=(a21/a19);
  a12=(a12+a21);
  a12=(-a12);
  a12=exp(a12);
  a21=arg[2] ? arg[2][130] : 0;
  a12=(a12*a21);
  a23=(a23-a13);
  a23=sq(a23);
  a23=(a23/a10);
  a26=(a26-a5);
  a26=sq(a26);
  a26=(a26/a6);
  a23=(a23+a26);
  a27=(a27-a0);
  a27=sq(a27);
  a27=(a27/a16);
  a23=(a23+a27);
  a28=(a28-a1);
  a28=sq(a28);
  a28=(a28/a17);
  a23=(a23+a28);
  a29=(a29-a7);
  a29=sq(a29);
  a29=(a29/a19);
  a23=(a23+a29);
  a23=(-a23);
  a23=exp(a23);
  a29=arg[2] ? arg[2][131] : 0;
  a23=(a23*a29);
  a12=(a12+a23);
  a25=(a25-a13);
  a25=sq(a25);
  a25=(a25/a10);
  a31=(a31-a5);
  a31=sq(a31);
  a31=(a31/a6);
  a25=(a25+a31);
  a32=(a32-a0);
  a32=sq(a32);
  a32=(a32/a16);
  a25=(a25+a32);
  a33=(a33-a1);
  a33=sq(a33);
  a33=(a33/a17);
  a25=(a25+a33);
  a34=(a34-a7);
  a34=sq(a34);
  a34=(a34/a19);
  a25=(a25+a34);
  a25=(-a25);
  a25=exp(a25);
  a34=arg[2] ? arg[2][132] : 0;
  a25=(a25*a34);
  a12=(a12+a25);
  a30=(a30-a13);
  a30=sq(a30);
  a30=(a30/a10);
  a36=(a36-a5);
  a36=sq(a36);
  a36=(a36/a6);
  a30=(a30+a36);
  a37=(a37-a0);
  a37=sq(a37);
  a37=(a37/a16);
  a30=(a30+a37);
  a38=(a38-a1);
  a38=sq(a38);
  a38=(a38/a17);
  a30=(a30+a38);
  a39=(a39-a7);
  a39=sq(a39);
  a39=(a39/a19);
  a30=(a30+a39);
  a30=(-a30);
  a30=exp(a30);
  a39=arg[2] ? arg[2][133] : 0;
  a30=(a30*a39);
  a12=(a12+a30);
  a35=(a35-a13);
  a35=sq(a35);
  a35=(a35/a10);
  a41=(a41-a5);
  a41=sq(a41);
  a41=(a41/a6);
  a35=(a35+a41);
  a42=(a42-a0);
  a42=sq(a42);
  a42=(a42/a16);
  a35=(a35+a42);
  a43=(a43-a1);
  a43=sq(a43);
  a43=(a43/a17);
  a35=(a35+a43);
  a44=(a44-a7);
  a44=sq(a44);
  a44=(a44/a19);
  a35=(a35+a44);
  a35=(-a35);
  a35=exp(a35);
  a44=arg[2] ? arg[2][134] : 0;
  a35=(a35*a44);
  a12=(a12+a35);
  a40=(a40-a13);
  a40=sq(a40);
  a40=(a40/a10);
  a46=(a46-a5);
  a46=sq(a46);
  a46=(a46/a6);
  a40=(a40+a46);
  a47=(a47-a0);
  a47=sq(a47);
  a47=(a47/a16);
  a40=(a40+a47);
  a48=(a48-a1);
  a48=sq(a48);
  a48=(a48/a17);
  a40=(a40+a48);
  a49=(a49-a7);
  a49=sq(a49);
  a49=(a49/a19);
  a40=(a40+a49);
  a40=(-a40);
  a40=exp(a40);
  a49=arg[2] ? arg[2][135] : 0;
  a40=(a40*a49);
  a12=(a12+a40);
  a45=(a45-a13);
  a45=sq(a45);
  a45=(a45/a10);
  a51=(a51-a5);
  a51=sq(a51);
  a51=(a51/a6);
  a45=(a45+a51);
  a52=(a52-a0);
  a52=sq(a52);
  a52=(a52/a16);
  a45=(a45+a52);
  a53=(a53-a1);
  a53=sq(a53);
  a53=(a53/a17);
  a45=(a45+a53);
  a54=(a54-a7);
  a54=sq(a54);
  a54=(a54/a19);
  a45=(a45+a54);
  a45=(-a45);
  a45=exp(a45);
  a54=arg[2] ? arg[2][136] : 0;
  a45=(a45*a54);
  a12=(a12+a45);
  a50=(a50-a13);
  a50=sq(a50);
  a50=(a50/a10);
  a56=(a56-a5);
  a56=sq(a56);
  a56=(a56/a6);
  a50=(a50+a56);
  a57=(a57-a0);
  a57=sq(a57);
  a57=(a57/a16);
  a50=(a50+a57);
  a58=(a58-a1);
  a58=sq(a58);
  a58=(a58/a17);
  a50=(a50+a58);
  a59=(a59-a7);
  a59=sq(a59);
  a59=(a59/a19);
  a50=(a50+a59);
  a50=(-a50);
  a50=exp(a50);
  a59=arg[2] ? arg[2][137] : 0;
  a50=(a50*a59);
  a12=(a12+a50);
  a55=(a55-a13);
  a55=sq(a55);
  a55=(a55/a10);
  a61=(a61-a5);
  a61=sq(a61);
  a61=(a61/a6);
  a55=(a55+a61);
  a62=(a62-a0);
  a62=sq(a62);
  a62=(a62/a16);
  a55=(a55+a62);
  a63=(a63-a1);
  a63=sq(a63);
  a63=(a63/a17);
  a55=(a55+a63);
  a64=(a64-a7);
  a64=sq(a64);
  a64=(a64/a19);
  a55=(a55+a64);
  a55=(-a55);
  a55=exp(a55);
  a64=arg[2] ? arg[2][138] : 0;
  a55=(a55*a64);
  a12=(a12+a55);
  a60=(a60-a13);
  a60=sq(a60);
  a60=(a60/a10);
  a66=(a66-a5);
  a66=sq(a66);
  a66=(a66/a6);
  a60=(a60+a66);
  a67=(a67-a0);
  a67=sq(a67);
  a67=(a67/a16);
  a60=(a60+a67);
  a68=(a68-a1);
  a68=sq(a68);
  a68=(a68/a17);
  a60=(a60+a68);
  a69=(a69-a7);
  a69=sq(a69);
  a69=(a69/a19);
  a60=(a60+a69);
  a60=(-a60);
  a60=exp(a60);
  a69=arg[2] ? arg[2][139] : 0;
  a60=(a60*a69);
  a12=(a12+a60);
  a65=(a65-a13);
  a65=sq(a65);
  a65=(a65/a10);
  a71=(a71-a5);
  a71=sq(a71);
  a71=(a71/a6);
  a65=(a65+a71);
  a72=(a72-a0);
  a72=sq(a72);
  a72=(a72/a16);
  a65=(a65+a72);
  a73=(a73-a1);
  a73=sq(a73);
  a73=(a73/a17);
  a65=(a65+a73);
  a74=(a74-a7);
  a74=sq(a74);
  a74=(a74/a19);
  a65=(a65+a74);
  a65=(-a65);
  a65=exp(a65);
  a74=arg[2] ? arg[2][140] : 0;
  a65=(a65*a74);
  a12=(a12+a65);
  a70=(a70-a13);
  a70=sq(a70);
  a70=(a70/a10);
  a76=(a76-a5);
  a76=sq(a76);
  a76=(a76/a6);
  a70=(a70+a76);
  a77=(a77-a0);
  a77=sq(a77);
  a77=(a77/a16);
  a70=(a70+a77);
  a78=(a78-a1);
  a78=sq(a78);
  a78=(a78/a17);
  a70=(a70+a78);
  a79=(a79-a7);
  a79=sq(a79);
  a79=(a79/a19);
  a70=(a70+a79);
  a70=(-a70);
  a70=exp(a70);
  a79=arg[2] ? arg[2][141] : 0;
  a70=(a70*a79);
  a12=(a12+a70);
  a75=(a75-a13);
  a75=sq(a75);
  a75=(a75/a10);
  a81=(a81-a5);
  a81=sq(a81);
  a81=(a81/a6);
  a75=(a75+a81);
  a82=(a82-a0);
  a82=sq(a82);
  a82=(a82/a16);
  a75=(a75+a82);
  a83=(a83-a1);
  a83=sq(a83);
  a83=(a83/a17);
  a75=(a75+a83);
  a84=(a84-a7);
  a84=sq(a84);
  a84=(a84/a19);
  a75=(a75+a84);
  a75=(-a75);
  a75=exp(a75);
  a84=arg[2] ? arg[2][142] : 0;
  a75=(a75*a84);
  a12=(a12+a75);
  a80=(a80-a13);
  a80=sq(a80);
  a80=(a80/a10);
  a86=(a86-a5);
  a86=sq(a86);
  a86=(a86/a6);
  a80=(a80+a86);
  a87=(a87-a0);
  a87=sq(a87);
  a87=(a87/a16);
  a80=(a80+a87);
  a88=(a88-a1);
  a88=sq(a88);
  a88=(a88/a17);
  a80=(a80+a88);
  a89=(a89-a7);
  a89=sq(a89);
  a89=(a89/a19);
  a80=(a80+a89);
  a80=(-a80);
  a80=exp(a80);
  a89=arg[2] ? arg[2][143] : 0;
  a80=(a80*a89);
  a12=(a12+a80);
  a85=(a85-a13);
  a85=sq(a85);
  a85=(a85/a10);
  a91=(a91-a5);
  a91=sq(a91);
  a91=(a91/a6);
  a85=(a85+a91);
  a92=(a92-a0);
  a92=sq(a92);
  a92=(a92/a16);
  a85=(a85+a92);
  a93=(a93-a1);
  a93=sq(a93);
  a93=(a93/a17);
  a85=(a85+a93);
  a94=(a94-a7);
  a94=sq(a94);
  a94=(a94/a19);
  a85=(a85+a94);
  a85=(-a85);
  a85=exp(a85);
  a94=arg[2] ? arg[2][144] : 0;
  a85=(a85*a94);
  a12=(a12+a85);
  a90=(a90-a13);
  a90=sq(a90);
  a90=(a90/a10);
  a96=(a96-a5);
  a96=sq(a96);
  a96=(a96/a6);
  a90=(a90+a96);
  a97=(a97-a0);
  a97=sq(a97);
  a97=(a97/a16);
  a90=(a90+a97);
  a98=(a98-a1);
  a98=sq(a98);
  a98=(a98/a17);
  a90=(a90+a98);
  a99=(a99-a7);
  a99=sq(a99);
  a99=(a99/a19);
  a90=(a90+a99);
  a90=(-a90);
  a90=exp(a90);
  a99=arg[2] ? arg[2][145] : 0;
  a90=(a90*a99);
  a12=(a12+a90);
  a95=(a95-a13);
  a95=sq(a95);
  a95=(a95/a10);
  a101=(a101-a5);
  a101=sq(a101);
  a101=(a101/a6);
  a95=(a95+a101);
  a102=(a102-a0);
  a102=sq(a102);
  a102=(a102/a16);
  a95=(a95+a102);
  a103=(a103-a1);
  a103=sq(a103);
  a103=(a103/a17);
  a95=(a95+a103);
  a104=(a104-a7);
  a104=sq(a104);
  a104=(a104/a19);
  a95=(a95+a104);
  a95=(-a95);
  a95=exp(a95);
  a104=arg[2] ? arg[2][146] : 0;
  a95=(a95*a104);
  a12=(a12+a95);
  a100=(a100-a13);
  a100=sq(a100);
  a100=(a100/a10);
  a106=(a106-a5);
  a106=sq(a106);
  a106=(a106/a6);
  a100=(a100+a106);
  a107=(a107-a0);
  a107=sq(a107);
  a107=(a107/a16);
  a100=(a100+a107);
  a108=(a108-a1);
  a108=sq(a108);
  a108=(a108/a17);
  a100=(a100+a108);
  a109=(a109-a7);
  a109=sq(a109);
  a109=(a109/a19);
  a100=(a100+a109);
  a100=(-a100);
  a100=exp(a100);
  a109=arg[2] ? arg[2][147] : 0;
  a100=(a100*a109);
  a12=(a12+a100);
  a105=(a105-a13);
  a105=sq(a105);
  a105=(a105/a10);
  a111=(a111-a5);
  a111=sq(a111);
  a111=(a111/a6);
  a105=(a105+a111);
  a112=(a112-a0);
  a112=sq(a112);
  a112=(a112/a16);
  a105=(a105+a112);
  a113=(a113-a1);
  a113=sq(a113);
  a113=(a113/a17);
  a105=(a105+a113);
  a114=(a114-a7);
  a114=sq(a114);
  a114=(a114/a19);
  a105=(a105+a114);
  a105=(-a105);
  a105=exp(a105);
  a114=arg[2] ? arg[2][148] : 0;
  a105=(a105*a114);
  a12=(a12+a105);
  a110=(a110-a13);
  a110=sq(a110);
  a110=(a110/a10);
  a15=(a15-a5);
  a15=sq(a15);
  a15=(a15/a6);
  a110=(a110+a15);
  a116=(a116-a0);
  a116=sq(a116);
  a116=(a116/a16);
  a110=(a110+a116);
  a18=(a18-a1);
  a18=sq(a18);
  a18=(a18/a17);
  a110=(a110+a18);
  a20=(a20-a7);
  a20=sq(a20);
  a20=(a20/a19);
  a110=(a110+a20);
  a110=(-a110);
  a110=exp(a110);
  a20=arg[2] ? arg[2][149] : 0;
  a110=(a110*a20);
  a12=(a12+a110);
  a11=(a11*a12);
  a4=(a4+a11);
  if (res[0]!=0) res[0][3]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    case 3: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 117;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_fun(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_fun\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_fun\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[319];
  const casadi_real* arg[4] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+164);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+4, casadi_s1, w+164);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+5, casadi_s2, w+164);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+160, casadi_s3, w+164);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+160;
  i = f_fun(arg, res, iw, w+164, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_fun\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "f_fun")==0) {
    return mex_f_fun(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_fun'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
