/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) gp_cont_fun_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[159] = {155, 1, 0, 155, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154};
static const int casadi_s3[4] = {0, 1, 0, 0};
static const int casadi_s4[6] = {2, 1, 0, 2, 0, 1};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* gp_cont_fun:(i0[4],i1,i2[155],i3[0])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[2] ? arg[2][5] : 0;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=(a0-a1);
  a2=sq(a2);
  casadi_real a3=arg[2] ? arg[2][125] : 0;
  a3=sq(a3);
  a2=(a2/a3);
  casadi_real a4=arg[2] ? arg[2][25] : 0;
  casadi_real a5=arg[0] ? arg[0][1] : 0;
  casadi_real a6=(a4-a5);
  a6=sq(a6);
  casadi_real a7=arg[2] ? arg[2][126] : 0;
  a7=sq(a7);
  a6=(a6/a7);
  a2=(a2+a6);
  a6=arg[2] ? arg[2][45] : 0;
  casadi_real a8=arg[0] ? arg[0][2] : 0;
  casadi_real a9=(a6-a8);
  a9=sq(a9);
  casadi_real a10=arg[2] ? arg[2][127] : 0;
  a10=sq(a10);
  a9=(a9/a10);
  a2=(a2+a9);
  a9=arg[2] ? arg[2][65] : 0;
  casadi_real a11=arg[0] ? arg[0][3] : 0;
  casadi_real a12=(a9-a11);
  a12=sq(a12);
  casadi_real a13=arg[2] ? arg[2][128] : 0;
  a13=sq(a13);
  a12=(a12/a13);
  a2=(a2+a12);
  a12=arg[2] ? arg[2][85] : 0;
  casadi_real a14=arg[1] ? arg[1][0] : 0;
  casadi_real a15=(a12-a14);
  a15=sq(a15);
  casadi_real a16=arg[2] ? arg[2][129] : 0;
  a16=sq(a16);
  a15=(a15/a16);
  a2=(a2+a15);
  a2=(-a2);
  a2=exp(a2);
  a15=arg[2] ? arg[2][105] : 0;
  a2=(a2*a15);
  a15=arg[2] ? arg[2][6] : 0;
  casadi_real a17=(a15-a1);
  a17=sq(a17);
  a17=(a17/a3);
  casadi_real a18=arg[2] ? arg[2][26] : 0;
  casadi_real a19=(a18-a5);
  a19=sq(a19);
  a19=(a19/a7);
  a17=(a17+a19);
  a19=arg[2] ? arg[2][46] : 0;
  casadi_real a20=(a19-a8);
  a20=sq(a20);
  a20=(a20/a10);
  a17=(a17+a20);
  a20=arg[2] ? arg[2][66] : 0;
  casadi_real a21=(a20-a11);
  a21=sq(a21);
  a21=(a21/a13);
  a17=(a17+a21);
  a21=arg[2] ? arg[2][86] : 0;
  casadi_real a22=(a21-a14);
  a22=sq(a22);
  a22=(a22/a16);
  a17=(a17+a22);
  a17=(-a17);
  a17=exp(a17);
  a22=arg[2] ? arg[2][106] : 0;
  a17=(a17*a22);
  a2=(a2+a17);
  a17=arg[2] ? arg[2][7] : 0;
  a22=(a17-a1);
  a22=sq(a22);
  a22=(a22/a3);
  casadi_real a23=arg[2] ? arg[2][27] : 0;
  casadi_real a24=(a23-a5);
  a24=sq(a24);
  a24=(a24/a7);
  a22=(a22+a24);
  a24=arg[2] ? arg[2][47] : 0;
  casadi_real a25=(a24-a8);
  a25=sq(a25);
  a25=(a25/a10);
  a22=(a22+a25);
  a25=arg[2] ? arg[2][67] : 0;
  casadi_real a26=(a25-a11);
  a26=sq(a26);
  a26=(a26/a13);
  a22=(a22+a26);
  a26=arg[2] ? arg[2][87] : 0;
  casadi_real a27=(a26-a14);
  a27=sq(a27);
  a27=(a27/a16);
  a22=(a22+a27);
  a22=(-a22);
  a22=exp(a22);
  a27=arg[2] ? arg[2][107] : 0;
  a22=(a22*a27);
  a2=(a2+a22);
  a22=arg[2] ? arg[2][8] : 0;
  a27=(a22-a1);
  a27=sq(a27);
  a27=(a27/a3);
  casadi_real a28=arg[2] ? arg[2][28] : 0;
  casadi_real a29=(a28-a5);
  a29=sq(a29);
  a29=(a29/a7);
  a27=(a27+a29);
  a29=arg[2] ? arg[2][48] : 0;
  casadi_real a30=(a29-a8);
  a30=sq(a30);
  a30=(a30/a10);
  a27=(a27+a30);
  a30=arg[2] ? arg[2][68] : 0;
  casadi_real a31=(a30-a11);
  a31=sq(a31);
  a31=(a31/a13);
  a27=(a27+a31);
  a31=arg[2] ? arg[2][88] : 0;
  casadi_real a32=(a31-a14);
  a32=sq(a32);
  a32=(a32/a16);
  a27=(a27+a32);
  a27=(-a27);
  a27=exp(a27);
  a32=arg[2] ? arg[2][108] : 0;
  a27=(a27*a32);
  a2=(a2+a27);
  a27=arg[2] ? arg[2][9] : 0;
  a32=(a27-a1);
  a32=sq(a32);
  a32=(a32/a3);
  casadi_real a33=arg[2] ? arg[2][29] : 0;
  casadi_real a34=(a33-a5);
  a34=sq(a34);
  a34=(a34/a7);
  a32=(a32+a34);
  a34=arg[2] ? arg[2][49] : 0;
  casadi_real a35=(a34-a8);
  a35=sq(a35);
  a35=(a35/a10);
  a32=(a32+a35);
  a35=arg[2] ? arg[2][69] : 0;
  casadi_real a36=(a35-a11);
  a36=sq(a36);
  a36=(a36/a13);
  a32=(a32+a36);
  a36=arg[2] ? arg[2][89] : 0;
  casadi_real a37=(a36-a14);
  a37=sq(a37);
  a37=(a37/a16);
  a32=(a32+a37);
  a32=(-a32);
  a32=exp(a32);
  a37=arg[2] ? arg[2][109] : 0;
  a32=(a32*a37);
  a2=(a2+a32);
  a32=arg[2] ? arg[2][10] : 0;
  a37=(a32-a1);
  a37=sq(a37);
  a37=(a37/a3);
  casadi_real a38=arg[2] ? arg[2][30] : 0;
  casadi_real a39=(a38-a5);
  a39=sq(a39);
  a39=(a39/a7);
  a37=(a37+a39);
  a39=arg[2] ? arg[2][50] : 0;
  casadi_real a40=(a39-a8);
  a40=sq(a40);
  a40=(a40/a10);
  a37=(a37+a40);
  a40=arg[2] ? arg[2][70] : 0;
  casadi_real a41=(a40-a11);
  a41=sq(a41);
  a41=(a41/a13);
  a37=(a37+a41);
  a41=arg[2] ? arg[2][90] : 0;
  casadi_real a42=(a41-a14);
  a42=sq(a42);
  a42=(a42/a16);
  a37=(a37+a42);
  a37=(-a37);
  a37=exp(a37);
  a42=arg[2] ? arg[2][110] : 0;
  a37=(a37*a42);
  a2=(a2+a37);
  a37=arg[2] ? arg[2][11] : 0;
  a42=(a37-a1);
  a42=sq(a42);
  a42=(a42/a3);
  casadi_real a43=arg[2] ? arg[2][31] : 0;
  casadi_real a44=(a43-a5);
  a44=sq(a44);
  a44=(a44/a7);
  a42=(a42+a44);
  a44=arg[2] ? arg[2][51] : 0;
  casadi_real a45=(a44-a8);
  a45=sq(a45);
  a45=(a45/a10);
  a42=(a42+a45);
  a45=arg[2] ? arg[2][71] : 0;
  casadi_real a46=(a45-a11);
  a46=sq(a46);
  a46=(a46/a13);
  a42=(a42+a46);
  a46=arg[2] ? arg[2][91] : 0;
  casadi_real a47=(a46-a14);
  a47=sq(a47);
  a47=(a47/a16);
  a42=(a42+a47);
  a42=(-a42);
  a42=exp(a42);
  a47=arg[2] ? arg[2][111] : 0;
  a42=(a42*a47);
  a2=(a2+a42);
  a42=arg[2] ? arg[2][12] : 0;
  a47=(a42-a1);
  a47=sq(a47);
  a47=(a47/a3);
  casadi_real a48=arg[2] ? arg[2][32] : 0;
  casadi_real a49=(a48-a5);
  a49=sq(a49);
  a49=(a49/a7);
  a47=(a47+a49);
  a49=arg[2] ? arg[2][52] : 0;
  casadi_real a50=(a49-a8);
  a50=sq(a50);
  a50=(a50/a10);
  a47=(a47+a50);
  a50=arg[2] ? arg[2][72] : 0;
  casadi_real a51=(a50-a11);
  a51=sq(a51);
  a51=(a51/a13);
  a47=(a47+a51);
  a51=arg[2] ? arg[2][92] : 0;
  casadi_real a52=(a51-a14);
  a52=sq(a52);
  a52=(a52/a16);
  a47=(a47+a52);
  a47=(-a47);
  a47=exp(a47);
  a52=arg[2] ? arg[2][112] : 0;
  a47=(a47*a52);
  a2=(a2+a47);
  a47=arg[2] ? arg[2][13] : 0;
  a52=(a47-a1);
  a52=sq(a52);
  a52=(a52/a3);
  casadi_real a53=arg[2] ? arg[2][33] : 0;
  casadi_real a54=(a53-a5);
  a54=sq(a54);
  a54=(a54/a7);
  a52=(a52+a54);
  a54=arg[2] ? arg[2][53] : 0;
  casadi_real a55=(a54-a8);
  a55=sq(a55);
  a55=(a55/a10);
  a52=(a52+a55);
  a55=arg[2] ? arg[2][73] : 0;
  casadi_real a56=(a55-a11);
  a56=sq(a56);
  a56=(a56/a13);
  a52=(a52+a56);
  a56=arg[2] ? arg[2][93] : 0;
  casadi_real a57=(a56-a14);
  a57=sq(a57);
  a57=(a57/a16);
  a52=(a52+a57);
  a52=(-a52);
  a52=exp(a52);
  a57=arg[2] ? arg[2][113] : 0;
  a52=(a52*a57);
  a2=(a2+a52);
  a52=arg[2] ? arg[2][14] : 0;
  a57=(a52-a1);
  a57=sq(a57);
  a57=(a57/a3);
  casadi_real a58=arg[2] ? arg[2][34] : 0;
  casadi_real a59=(a58-a5);
  a59=sq(a59);
  a59=(a59/a7);
  a57=(a57+a59);
  a59=arg[2] ? arg[2][54] : 0;
  casadi_real a60=(a59-a8);
  a60=sq(a60);
  a60=(a60/a10);
  a57=(a57+a60);
  a60=arg[2] ? arg[2][74] : 0;
  casadi_real a61=(a60-a11);
  a61=sq(a61);
  a61=(a61/a13);
  a57=(a57+a61);
  a61=arg[2] ? arg[2][94] : 0;
  casadi_real a62=(a61-a14);
  a62=sq(a62);
  a62=(a62/a16);
  a57=(a57+a62);
  a57=(-a57);
  a57=exp(a57);
  a62=arg[2] ? arg[2][114] : 0;
  a57=(a57*a62);
  a2=(a2+a57);
  a57=arg[2] ? arg[2][15] : 0;
  a62=(a57-a1);
  a62=sq(a62);
  a62=(a62/a3);
  casadi_real a63=arg[2] ? arg[2][35] : 0;
  casadi_real a64=(a63-a5);
  a64=sq(a64);
  a64=(a64/a7);
  a62=(a62+a64);
  a64=arg[2] ? arg[2][55] : 0;
  casadi_real a65=(a64-a8);
  a65=sq(a65);
  a65=(a65/a10);
  a62=(a62+a65);
  a65=arg[2] ? arg[2][75] : 0;
  casadi_real a66=(a65-a11);
  a66=sq(a66);
  a66=(a66/a13);
  a62=(a62+a66);
  a66=arg[2] ? arg[2][95] : 0;
  casadi_real a67=(a66-a14);
  a67=sq(a67);
  a67=(a67/a16);
  a62=(a62+a67);
  a62=(-a62);
  a62=exp(a62);
  a67=arg[2] ? arg[2][115] : 0;
  a62=(a62*a67);
  a2=(a2+a62);
  a62=arg[2] ? arg[2][16] : 0;
  a67=(a62-a1);
  a67=sq(a67);
  a67=(a67/a3);
  casadi_real a68=arg[2] ? arg[2][36] : 0;
  casadi_real a69=(a68-a5);
  a69=sq(a69);
  a69=(a69/a7);
  a67=(a67+a69);
  a69=arg[2] ? arg[2][56] : 0;
  casadi_real a70=(a69-a8);
  a70=sq(a70);
  a70=(a70/a10);
  a67=(a67+a70);
  a70=arg[2] ? arg[2][76] : 0;
  casadi_real a71=(a70-a11);
  a71=sq(a71);
  a71=(a71/a13);
  a67=(a67+a71);
  a71=arg[2] ? arg[2][96] : 0;
  casadi_real a72=(a71-a14);
  a72=sq(a72);
  a72=(a72/a16);
  a67=(a67+a72);
  a67=(-a67);
  a67=exp(a67);
  a72=arg[2] ? arg[2][116] : 0;
  a67=(a67*a72);
  a2=(a2+a67);
  a67=arg[2] ? arg[2][17] : 0;
  a72=(a67-a1);
  a72=sq(a72);
  a72=(a72/a3);
  casadi_real a73=arg[2] ? arg[2][37] : 0;
  casadi_real a74=(a73-a5);
  a74=sq(a74);
  a74=(a74/a7);
  a72=(a72+a74);
  a74=arg[2] ? arg[2][57] : 0;
  casadi_real a75=(a74-a8);
  a75=sq(a75);
  a75=(a75/a10);
  a72=(a72+a75);
  a75=arg[2] ? arg[2][77] : 0;
  casadi_real a76=(a75-a11);
  a76=sq(a76);
  a76=(a76/a13);
  a72=(a72+a76);
  a76=arg[2] ? arg[2][97] : 0;
  casadi_real a77=(a76-a14);
  a77=sq(a77);
  a77=(a77/a16);
  a72=(a72+a77);
  a72=(-a72);
  a72=exp(a72);
  a77=arg[2] ? arg[2][117] : 0;
  a72=(a72*a77);
  a2=(a2+a72);
  a72=arg[2] ? arg[2][18] : 0;
  a77=(a72-a1);
  a77=sq(a77);
  a77=(a77/a3);
  casadi_real a78=arg[2] ? arg[2][38] : 0;
  casadi_real a79=(a78-a5);
  a79=sq(a79);
  a79=(a79/a7);
  a77=(a77+a79);
  a79=arg[2] ? arg[2][58] : 0;
  casadi_real a80=(a79-a8);
  a80=sq(a80);
  a80=(a80/a10);
  a77=(a77+a80);
  a80=arg[2] ? arg[2][78] : 0;
  casadi_real a81=(a80-a11);
  a81=sq(a81);
  a81=(a81/a13);
  a77=(a77+a81);
  a81=arg[2] ? arg[2][98] : 0;
  casadi_real a82=(a81-a14);
  a82=sq(a82);
  a82=(a82/a16);
  a77=(a77+a82);
  a77=(-a77);
  a77=exp(a77);
  a82=arg[2] ? arg[2][118] : 0;
  a77=(a77*a82);
  a2=(a2+a77);
  a77=arg[2] ? arg[2][19] : 0;
  a82=(a77-a1);
  a82=sq(a82);
  a82=(a82/a3);
  casadi_real a83=arg[2] ? arg[2][39] : 0;
  casadi_real a84=(a83-a5);
  a84=sq(a84);
  a84=(a84/a7);
  a82=(a82+a84);
  a84=arg[2] ? arg[2][59] : 0;
  casadi_real a85=(a84-a8);
  a85=sq(a85);
  a85=(a85/a10);
  a82=(a82+a85);
  a85=arg[2] ? arg[2][79] : 0;
  casadi_real a86=(a85-a11);
  a86=sq(a86);
  a86=(a86/a13);
  a82=(a82+a86);
  a86=arg[2] ? arg[2][99] : 0;
  casadi_real a87=(a86-a14);
  a87=sq(a87);
  a87=(a87/a16);
  a82=(a82+a87);
  a82=(-a82);
  a82=exp(a82);
  a87=arg[2] ? arg[2][119] : 0;
  a82=(a82*a87);
  a2=(a2+a82);
  a82=arg[2] ? arg[2][20] : 0;
  a87=(a82-a1);
  a87=sq(a87);
  a87=(a87/a3);
  casadi_real a88=arg[2] ? arg[2][40] : 0;
  casadi_real a89=(a88-a5);
  a89=sq(a89);
  a89=(a89/a7);
  a87=(a87+a89);
  a89=arg[2] ? arg[2][60] : 0;
  casadi_real a90=(a89-a8);
  a90=sq(a90);
  a90=(a90/a10);
  a87=(a87+a90);
  a90=arg[2] ? arg[2][80] : 0;
  casadi_real a91=(a90-a11);
  a91=sq(a91);
  a91=(a91/a13);
  a87=(a87+a91);
  a91=arg[2] ? arg[2][100] : 0;
  casadi_real a92=(a91-a14);
  a92=sq(a92);
  a92=(a92/a16);
  a87=(a87+a92);
  a87=(-a87);
  a87=exp(a87);
  a92=arg[2] ? arg[2][120] : 0;
  a87=(a87*a92);
  a2=(a2+a87);
  a87=arg[2] ? arg[2][21] : 0;
  a92=(a87-a1);
  a92=sq(a92);
  a92=(a92/a3);
  casadi_real a93=arg[2] ? arg[2][41] : 0;
  casadi_real a94=(a93-a5);
  a94=sq(a94);
  a94=(a94/a7);
  a92=(a92+a94);
  a94=arg[2] ? arg[2][61] : 0;
  casadi_real a95=(a94-a8);
  a95=sq(a95);
  a95=(a95/a10);
  a92=(a92+a95);
  a95=arg[2] ? arg[2][81] : 0;
  casadi_real a96=(a95-a11);
  a96=sq(a96);
  a96=(a96/a13);
  a92=(a92+a96);
  a96=arg[2] ? arg[2][101] : 0;
  casadi_real a97=(a96-a14);
  a97=sq(a97);
  a97=(a97/a16);
  a92=(a92+a97);
  a92=(-a92);
  a92=exp(a92);
  a97=arg[2] ? arg[2][121] : 0;
  a92=(a92*a97);
  a2=(a2+a92);
  a92=arg[2] ? arg[2][22] : 0;
  a97=(a92-a1);
  a97=sq(a97);
  a97=(a97/a3);
  casadi_real a98=arg[2] ? arg[2][42] : 0;
  casadi_real a99=(a98-a5);
  a99=sq(a99);
  a99=(a99/a7);
  a97=(a97+a99);
  a99=arg[2] ? arg[2][62] : 0;
  casadi_real a100=(a99-a8);
  a100=sq(a100);
  a100=(a100/a10);
  a97=(a97+a100);
  a100=arg[2] ? arg[2][82] : 0;
  casadi_real a101=(a100-a11);
  a101=sq(a101);
  a101=(a101/a13);
  a97=(a97+a101);
  a101=arg[2] ? arg[2][102] : 0;
  casadi_real a102=(a101-a14);
  a102=sq(a102);
  a102=(a102/a16);
  a97=(a97+a102);
  a97=(-a97);
  a97=exp(a97);
  a102=arg[2] ? arg[2][122] : 0;
  a97=(a97*a102);
  a2=(a2+a97);
  a97=arg[2] ? arg[2][23] : 0;
  a102=(a97-a1);
  a102=sq(a102);
  a102=(a102/a3);
  casadi_real a103=arg[2] ? arg[2][43] : 0;
  casadi_real a104=(a103-a5);
  a104=sq(a104);
  a104=(a104/a7);
  a102=(a102+a104);
  a104=arg[2] ? arg[2][63] : 0;
  casadi_real a105=(a104-a8);
  a105=sq(a105);
  a105=(a105/a10);
  a102=(a102+a105);
  a105=arg[2] ? arg[2][83] : 0;
  casadi_real a106=(a105-a11);
  a106=sq(a106);
  a106=(a106/a13);
  a102=(a102+a106);
  a106=arg[2] ? arg[2][103] : 0;
  casadi_real a107=(a106-a14);
  a107=sq(a107);
  a107=(a107/a16);
  a102=(a102+a107);
  a102=(-a102);
  a102=exp(a102);
  a107=arg[2] ? arg[2][123] : 0;
  a102=(a102*a107);
  a2=(a2+a102);
  a102=arg[2] ? arg[2][24] : 0;
  a107=(a102-a1);
  a107=sq(a107);
  a107=(a107/a3);
  a3=arg[2] ? arg[2][44] : 0;
  casadi_real a108=(a3-a5);
  a108=sq(a108);
  a108=(a108/a7);
  a107=(a107+a108);
  a108=arg[2] ? arg[2][64] : 0;
  a7=(a108-a8);
  a7=sq(a7);
  a7=(a7/a10);
  a107=(a107+a7);
  a7=arg[2] ? arg[2][84] : 0;
  a10=(a7-a11);
  a10=sq(a10);
  a10=(a10/a13);
  a107=(a107+a10);
  a10=arg[2] ? arg[2][104] : 0;
  a13=(a10-a14);
  a13=sq(a13);
  a13=(a13/a16);
  a107=(a107+a13);
  a107=(-a107);
  a107=exp(a107);
  a13=arg[2] ? arg[2][124] : 0;
  a107=(a107*a13);
  a2=(a2+a107);
  if (res[0]!=0) res[0][0]=a2;
  a0=(a0-a1);
  a0=sq(a0);
  a2=arg[2] ? arg[2][150] : 0;
  a2=sq(a2);
  a0=(a0/a2);
  a4=(a4-a5);
  a4=sq(a4);
  a107=arg[2] ? arg[2][151] : 0;
  a107=sq(a107);
  a4=(a4/a107);
  a0=(a0+a4);
  a6=(a6-a8);
  a6=sq(a6);
  a4=arg[2] ? arg[2][152] : 0;
  a4=sq(a4);
  a6=(a6/a4);
  a0=(a0+a6);
  a9=(a9-a11);
  a9=sq(a9);
  a6=arg[2] ? arg[2][153] : 0;
  a6=sq(a6);
  a9=(a9/a6);
  a0=(a0+a9);
  a12=(a12-a14);
  a12=sq(a12);
  a9=arg[2] ? arg[2][154] : 0;
  a9=sq(a9);
  a12=(a12/a9);
  a0=(a0+a12);
  a0=(-a0);
  a0=exp(a0);
  a12=arg[2] ? arg[2][130] : 0;
  a0=(a0*a12);
  a15=(a15-a1);
  a15=sq(a15);
  a15=(a15/a2);
  a18=(a18-a5);
  a18=sq(a18);
  a18=(a18/a107);
  a15=(a15+a18);
  a19=(a19-a8);
  a19=sq(a19);
  a19=(a19/a4);
  a15=(a15+a19);
  a20=(a20-a11);
  a20=sq(a20);
  a20=(a20/a6);
  a15=(a15+a20);
  a21=(a21-a14);
  a21=sq(a21);
  a21=(a21/a9);
  a15=(a15+a21);
  a15=(-a15);
  a15=exp(a15);
  a21=arg[2] ? arg[2][131] : 0;
  a15=(a15*a21);
  a0=(a0+a15);
  a17=(a17-a1);
  a17=sq(a17);
  a17=(a17/a2);
  a23=(a23-a5);
  a23=sq(a23);
  a23=(a23/a107);
  a17=(a17+a23);
  a24=(a24-a8);
  a24=sq(a24);
  a24=(a24/a4);
  a17=(a17+a24);
  a25=(a25-a11);
  a25=sq(a25);
  a25=(a25/a6);
  a17=(a17+a25);
  a26=(a26-a14);
  a26=sq(a26);
  a26=(a26/a9);
  a17=(a17+a26);
  a17=(-a17);
  a17=exp(a17);
  a26=arg[2] ? arg[2][132] : 0;
  a17=(a17*a26);
  a0=(a0+a17);
  a22=(a22-a1);
  a22=sq(a22);
  a22=(a22/a2);
  a28=(a28-a5);
  a28=sq(a28);
  a28=(a28/a107);
  a22=(a22+a28);
  a29=(a29-a8);
  a29=sq(a29);
  a29=(a29/a4);
  a22=(a22+a29);
  a30=(a30-a11);
  a30=sq(a30);
  a30=(a30/a6);
  a22=(a22+a30);
  a31=(a31-a14);
  a31=sq(a31);
  a31=(a31/a9);
  a22=(a22+a31);
  a22=(-a22);
  a22=exp(a22);
  a31=arg[2] ? arg[2][133] : 0;
  a22=(a22*a31);
  a0=(a0+a22);
  a27=(a27-a1);
  a27=sq(a27);
  a27=(a27/a2);
  a33=(a33-a5);
  a33=sq(a33);
  a33=(a33/a107);
  a27=(a27+a33);
  a34=(a34-a8);
  a34=sq(a34);
  a34=(a34/a4);
  a27=(a27+a34);
  a35=(a35-a11);
  a35=sq(a35);
  a35=(a35/a6);
  a27=(a27+a35);
  a36=(a36-a14);
  a36=sq(a36);
  a36=(a36/a9);
  a27=(a27+a36);
  a27=(-a27);
  a27=exp(a27);
  a36=arg[2] ? arg[2][134] : 0;
  a27=(a27*a36);
  a0=(a0+a27);
  a32=(a32-a1);
  a32=sq(a32);
  a32=(a32/a2);
  a38=(a38-a5);
  a38=sq(a38);
  a38=(a38/a107);
  a32=(a32+a38);
  a39=(a39-a8);
  a39=sq(a39);
  a39=(a39/a4);
  a32=(a32+a39);
  a40=(a40-a11);
  a40=sq(a40);
  a40=(a40/a6);
  a32=(a32+a40);
  a41=(a41-a14);
  a41=sq(a41);
  a41=(a41/a9);
  a32=(a32+a41);
  a32=(-a32);
  a32=exp(a32);
  a41=arg[2] ? arg[2][135] : 0;
  a32=(a32*a41);
  a0=(a0+a32);
  a37=(a37-a1);
  a37=sq(a37);
  a37=(a37/a2);
  a43=(a43-a5);
  a43=sq(a43);
  a43=(a43/a107);
  a37=(a37+a43);
  a44=(a44-a8);
  a44=sq(a44);
  a44=(a44/a4);
  a37=(a37+a44);
  a45=(a45-a11);
  a45=sq(a45);
  a45=(a45/a6);
  a37=(a37+a45);
  a46=(a46-a14);
  a46=sq(a46);
  a46=(a46/a9);
  a37=(a37+a46);
  a37=(-a37);
  a37=exp(a37);
  a46=arg[2] ? arg[2][136] : 0;
  a37=(a37*a46);
  a0=(a0+a37);
  a42=(a42-a1);
  a42=sq(a42);
  a42=(a42/a2);
  a48=(a48-a5);
  a48=sq(a48);
  a48=(a48/a107);
  a42=(a42+a48);
  a49=(a49-a8);
  a49=sq(a49);
  a49=(a49/a4);
  a42=(a42+a49);
  a50=(a50-a11);
  a50=sq(a50);
  a50=(a50/a6);
  a42=(a42+a50);
  a51=(a51-a14);
  a51=sq(a51);
  a51=(a51/a9);
  a42=(a42+a51);
  a42=(-a42);
  a42=exp(a42);
  a51=arg[2] ? arg[2][137] : 0;
  a42=(a42*a51);
  a0=(a0+a42);
  a47=(a47-a1);
  a47=sq(a47);
  a47=(a47/a2);
  a53=(a53-a5);
  a53=sq(a53);
  a53=(a53/a107);
  a47=(a47+a53);
  a54=(a54-a8);
  a54=sq(a54);
  a54=(a54/a4);
  a47=(a47+a54);
  a55=(a55-a11);
  a55=sq(a55);
  a55=(a55/a6);
  a47=(a47+a55);
  a56=(a56-a14);
  a56=sq(a56);
  a56=(a56/a9);
  a47=(a47+a56);
  a47=(-a47);
  a47=exp(a47);
  a56=arg[2] ? arg[2][138] : 0;
  a47=(a47*a56);
  a0=(a0+a47);
  a52=(a52-a1);
  a52=sq(a52);
  a52=(a52/a2);
  a58=(a58-a5);
  a58=sq(a58);
  a58=(a58/a107);
  a52=(a52+a58);
  a59=(a59-a8);
  a59=sq(a59);
  a59=(a59/a4);
  a52=(a52+a59);
  a60=(a60-a11);
  a60=sq(a60);
  a60=(a60/a6);
  a52=(a52+a60);
  a61=(a61-a14);
  a61=sq(a61);
  a61=(a61/a9);
  a52=(a52+a61);
  a52=(-a52);
  a52=exp(a52);
  a61=arg[2] ? arg[2][139] : 0;
  a52=(a52*a61);
  a0=(a0+a52);
  a57=(a57-a1);
  a57=sq(a57);
  a57=(a57/a2);
  a63=(a63-a5);
  a63=sq(a63);
  a63=(a63/a107);
  a57=(a57+a63);
  a64=(a64-a8);
  a64=sq(a64);
  a64=(a64/a4);
  a57=(a57+a64);
  a65=(a65-a11);
  a65=sq(a65);
  a65=(a65/a6);
  a57=(a57+a65);
  a66=(a66-a14);
  a66=sq(a66);
  a66=(a66/a9);
  a57=(a57+a66);
  a57=(-a57);
  a57=exp(a57);
  a66=arg[2] ? arg[2][140] : 0;
  a57=(a57*a66);
  a0=(a0+a57);
  a62=(a62-a1);
  a62=sq(a62);
  a62=(a62/a2);
  a68=(a68-a5);
  a68=sq(a68);
  a68=(a68/a107);
  a62=(a62+a68);
  a69=(a69-a8);
  a69=sq(a69);
  a69=(a69/a4);
  a62=(a62+a69);
  a70=(a70-a11);
  a70=sq(a70);
  a70=(a70/a6);
  a62=(a62+a70);
  a71=(a71-a14);
  a71=sq(a71);
  a71=(a71/a9);
  a62=(a62+a71);
  a62=(-a62);
  a62=exp(a62);
  a71=arg[2] ? arg[2][141] : 0;
  a62=(a62*a71);
  a0=(a0+a62);
  a67=(a67-a1);
  a67=sq(a67);
  a67=(a67/a2);
  a73=(a73-a5);
  a73=sq(a73);
  a73=(a73/a107);
  a67=(a67+a73);
  a74=(a74-a8);
  a74=sq(a74);
  a74=(a74/a4);
  a67=(a67+a74);
  a75=(a75-a11);
  a75=sq(a75);
  a75=(a75/a6);
  a67=(a67+a75);
  a76=(a76-a14);
  a76=sq(a76);
  a76=(a76/a9);
  a67=(a67+a76);
  a67=(-a67);
  a67=exp(a67);
  a76=arg[2] ? arg[2][142] : 0;
  a67=(a67*a76);
  a0=(a0+a67);
  a72=(a72-a1);
  a72=sq(a72);
  a72=(a72/a2);
  a78=(a78-a5);
  a78=sq(a78);
  a78=(a78/a107);
  a72=(a72+a78);
  a79=(a79-a8);
  a79=sq(a79);
  a79=(a79/a4);
  a72=(a72+a79);
  a80=(a80-a11);
  a80=sq(a80);
  a80=(a80/a6);
  a72=(a72+a80);
  a81=(a81-a14);
  a81=sq(a81);
  a81=(a81/a9);
  a72=(a72+a81);
  a72=(-a72);
  a72=exp(a72);
  a81=arg[2] ? arg[2][143] : 0;
  a72=(a72*a81);
  a0=(a0+a72);
  a77=(a77-a1);
  a77=sq(a77);
  a77=(a77/a2);
  a83=(a83-a5);
  a83=sq(a83);
  a83=(a83/a107);
  a77=(a77+a83);
  a84=(a84-a8);
  a84=sq(a84);
  a84=(a84/a4);
  a77=(a77+a84);
  a85=(a85-a11);
  a85=sq(a85);
  a85=(a85/a6);
  a77=(a77+a85);
  a86=(a86-a14);
  a86=sq(a86);
  a86=(a86/a9);
  a77=(a77+a86);
  a77=(-a77);
  a77=exp(a77);
  a86=arg[2] ? arg[2][144] : 0;
  a77=(a77*a86);
  a0=(a0+a77);
  a82=(a82-a1);
  a82=sq(a82);
  a82=(a82/a2);
  a88=(a88-a5);
  a88=sq(a88);
  a88=(a88/a107);
  a82=(a82+a88);
  a89=(a89-a8);
  a89=sq(a89);
  a89=(a89/a4);
  a82=(a82+a89);
  a90=(a90-a11);
  a90=sq(a90);
  a90=(a90/a6);
  a82=(a82+a90);
  a91=(a91-a14);
  a91=sq(a91);
  a91=(a91/a9);
  a82=(a82+a91);
  a82=(-a82);
  a82=exp(a82);
  a91=arg[2] ? arg[2][145] : 0;
  a82=(a82*a91);
  a0=(a0+a82);
  a87=(a87-a1);
  a87=sq(a87);
  a87=(a87/a2);
  a93=(a93-a5);
  a93=sq(a93);
  a93=(a93/a107);
  a87=(a87+a93);
  a94=(a94-a8);
  a94=sq(a94);
  a94=(a94/a4);
  a87=(a87+a94);
  a95=(a95-a11);
  a95=sq(a95);
  a95=(a95/a6);
  a87=(a87+a95);
  a96=(a96-a14);
  a96=sq(a96);
  a96=(a96/a9);
  a87=(a87+a96);
  a87=(-a87);
  a87=exp(a87);
  a96=arg[2] ? arg[2][146] : 0;
  a87=(a87*a96);
  a0=(a0+a87);
  a92=(a92-a1);
  a92=sq(a92);
  a92=(a92/a2);
  a98=(a98-a5);
  a98=sq(a98);
  a98=(a98/a107);
  a92=(a92+a98);
  a99=(a99-a8);
  a99=sq(a99);
  a99=(a99/a4);
  a92=(a92+a99);
  a100=(a100-a11);
  a100=sq(a100);
  a100=(a100/a6);
  a92=(a92+a100);
  a101=(a101-a14);
  a101=sq(a101);
  a101=(a101/a9);
  a92=(a92+a101);
  a92=(-a92);
  a92=exp(a92);
  a101=arg[2] ? arg[2][147] : 0;
  a92=(a92*a101);
  a0=(a0+a92);
  a97=(a97-a1);
  a97=sq(a97);
  a97=(a97/a2);
  a103=(a103-a5);
  a103=sq(a103);
  a103=(a103/a107);
  a97=(a97+a103);
  a104=(a104-a8);
  a104=sq(a104);
  a104=(a104/a4);
  a97=(a97+a104);
  a105=(a105-a11);
  a105=sq(a105);
  a105=(a105/a6);
  a97=(a97+a105);
  a106=(a106-a14);
  a106=sq(a106);
  a106=(a106/a9);
  a97=(a97+a106);
  a97=(-a97);
  a97=exp(a97);
  a106=arg[2] ? arg[2][148] : 0;
  a97=(a97*a106);
  a0=(a0+a97);
  a102=(a102-a1);
  a102=sq(a102);
  a102=(a102/a2);
  a3=(a3-a5);
  a3=sq(a3);
  a3=(a3/a107);
  a102=(a102+a3);
  a108=(a108-a8);
  a108=sq(a108);
  a108=(a108/a4);
  a102=(a102+a108);
  a7=(a7-a11);
  a7=sq(a7);
  a7=(a7/a6);
  a102=(a102+a7);
  a10=(a10-a14);
  a10=sq(a10);
  a10=(a10/a9);
  a102=(a102+a10);
  a102=(-a102);
  a102=exp(a102);
  a10=arg[2] ? arg[2][149] : 0;
  a102=(a102*a10);
  a0=(a0+a102);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gp_cont_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gp_cont_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gp_cont_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gp_cont_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int gp_cont_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* gp_cont_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gp_cont_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gp_cont_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gp_cont_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gp_cont_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 109;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_gp_cont_fun(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"gp_cont_fun\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"gp_cont_fun\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[317];
  const casadi_real* arg[4] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+162);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+4, casadi_s1, w+162);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+5, casadi_s2, w+162);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+160, casadi_s3, w+162);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+160;
  i = gp_cont_fun(arg, res, iw, w+162, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"gp_cont_fun\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s4, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[12];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "gp_cont_fun")==0) {
    return mex_gp_cont_fun(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'gp_cont_fun'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
